export const INCREMENT = "INCREMENT"
export const DECREMENT = "DECREMENT"
export const INCOME = "INCOME"
export const EXPENSE = "EXPENSE"
export const DELETEINCOME = "DELETEINCOME"
export const DELETEEXPENSE = "DELETEEXPENSE"